### ISSUE TITLE
docs.rsのビルドがコケてる

### ISSUE THREAD

**Issue by sksat** [sksat/rdfmt-rs#12]
- https://docs.rs/crate/rdfmt/0.1.0/builds
- かなしい

**Comment by sksat** [comment]
どうやらdocs.rsの自動ビルドはNetwork Access完全にダメっぽい．正しい．

**Comment by sksat** [comment]
Git submoduleにすべきかなあとも思ったけど，欲しいのはJSON Schemaだけなんだよなと思ってやめたんだよな

**Comment by sksat** [comment]
お？`.gitmodule`，`branch = TAG`いけるじゃん

**Comment by sksat** [comment]
> お？`.gitmodule`，`branch = TAG`いけるじゃん

いけないけどね

**Comment by sksat** [comment]
あと実は`cargo publish`時に自分でビルドしたやつ持ってけたりしないんかな

**Comment by sksat** [comment]
`cargo package`がまずそういうかんじじゃないな

**Comment by sksat** [comment]
ローカルにJSON Schemaが入ってたらそれを使うようにする & `cargo publish --allow-dirty`，がいいかもしれない．ちょっと気持ち悪いけれど(CIでやるようにすれば多少マシではある)

**Comment by sksat** [comment]
GitHub Actionsから`cargo publish`すんのって若干どうよと思わなくもなかったが，よく考えたら crates.io がGitHubでログインしてる(というかそれしかできない)ので別にいいかになった

**Comment by sksat** [comment]
まだうまくいくかはわからんためreopen

**Comment by sksat** [comment]
mainで
```sh
$ cargo b --features build-with-local-schema
$ cargo publish --features default,build-with-local-schema --allow-dirty
```
を実行

**Comment by sksat** [comment]
待機会場
https://docs.rs/crate/rdfmt/latest/builds

**Comment by sksat** [comment]
しかしこれだと結局Gitで管理されてないだけでcrateのtarballにはjsonschema埋まってんだよな

**Comment by sksat** [comment]
あ， #10 とかマージした後なのにpatch上げちゃった

**Comment by sksat** [comment]
ここでコケたあ
https://github.com/sksat/rdfmt-rs/blob/a12eae5b9dde125fb1c046a5f9ace937a1054192/build.rs#L45

**Comment by sksat** [comment]
v0.1.2をリリースして再実行

**Comment by sksat** [comment]
またコケとる

**Comment by sksat** [comment]
それはそうなんだわ
https://github.com/sksat/rdfmt-rs/blob/d4a6936616a5f6a56cb9c8f27a1272bfdbc492ea/build.rs#L50
> `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', build.rs:50:33

**Comment by sksat** [comment]
v0.1.3をリリースして再試行

**Comment by sksat** [comment]
```
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:181:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'extern-html-root-url'

error: could not document `rdfmt`
```
カス！！！！！！！！

**Comment by sksat** [comment]
まずdocs.rsで`rust-toolchain`が効かない(`Cargo.lock`から見る)のがカスでしょ

**Comment by sksat** [comment]
うわー，マジでnightlyで`cargo doc`したら死ぬわ

**Comment by sksat** [comment]
`crate-version`がまず2020年に入ったやつっぽいな

**Comment by sksat** [comment]
```
$ cargo +nightly b -Z crate-versions
warning: flag `-Z crate-versions` has been stabilized in the 1.47 release, and is no longer necessary
  The crate version is now automatically added to the documentation.

   Compiling rdfmt v0.1.3 (/home/sksat/prog/rdfmt-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.92s
```
アーハン

**Comment by sksat** [comment]
https://github.com/rust-lang/cargo/blob/35e82eb45f10de09e2a4b8e5f15a1c9adbd34680/src/cargo/core/compiler/mod.rs#L748-L761
ここらへんがダメそう

**Comment by sksat** [comment]
```bash
$ env RUSTDOCFLAGS='-v' cargo doc
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:199:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `rdfmt`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name rdfmt src/lib.rs -o /home/sksat/prog/rdfmt-rs/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi -C metadata=4f4a0f890cba6fe6 -L dependency=/home/sksat/prog/rdfmt-rs/target/debug/deps --extern schemafy=/home/sksat/prog/rdfmt-rs/target/debug/deps/libschemafy-7a2d8e102fe8fcd2.so --extern serde=/home/sksat/prog/rdfmt-rs/target/debug/deps/libserde-7d419297a6d8d214.rmeta --extern serde_json=/home/sksat/prog/rdfmt-rs/target/debug/deps/libserde_json-be1c91fe357b9688.rmeta --extern serde_variant=/home/sksat/prog/rdfmt-rs/target/debug/deps/libserde_variant-76267bb47169b2ba.rmeta -v --crate-version 0.1.3` (exit status: 1)
```
だめだが

**Comment by sksat** [comment]
0.58.0でもあるけどな
https://github.com/rust-lang/cargo/blob/b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb/src/cargo/core/compiler/mod.rs#L655

**Comment by sksat** [comment]
結構前に入ってるので普通にバグってる？

**Comment by sksat** [comment]
あーいやこれ`crate-version`をオーバーライドするためのPRか

**Comment by sksat** [comment]
beta(1.58.0)だと大丈夫だな

**Comment by sksat** [comment]
しかし当たり前だけどここらへんのテストは通ってんだよな
https://github.com/rust-lang/cargo/blob/35e82eb45f10de09e2a4b8e5f15a1c9adbd34680/tests/testsuite/doc.rs#L1923-L1952

**Comment by sksat** [comment]
`error: Unrecognized option: 'crate-version'`ばかり気にしてたけど，よく見たらその前にここでpanicしてんだよな
https://github.com/rust-lang/rust/blob/abbead78f7ab2d27ebf556970695472d1cdad44e/src/librustdoc/passes/mod.rs#L199

**Comment by sksat** [comment]
`src/lib.rs`にdoc commentが皆無だとこのexpectが爆発するようになっている(ただしこのコードは3年前: https://github.com/rust-lang/rust/commit/ee10d99b9a44c57f450678310b16e651d08075cd からあるがnightlyでだけ発動する)．
`src/lib.rs`にdoc commentを追加するとこのexpectは爆発しなくなるが，`error: Unrecognized option: 'crate-version'`は相変わらず出現する．

**Comment by sksat** [comment]
そろそろ再現用PR切るか．`docs.rs`固有の問題ではなくなったし．

**Comment by sksat** [comment]
何もしてないのにexpect爆発が消えた...なぜ...

**Comment by sksat** [comment]
v0.2.0-rc.1をリリースして再試行

**Comment by sksat** [comment]
気絶してたがビルド通ってそう

**Comment by sksat** [comment]
大丈夫そうだな．0.2.0リリースするか

**Comment by sksat** [comment]
なんも覚えてないけどそろそろ直ってないですかね
